# Generated by Django 4.2.4 on 2023-08-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.TextField()),
                ("file_hash", models.CharField(max_length=50)),
                ("file_size", models.IntegerField()),
                ("file_upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
