# Generated by Django 4.2.4 on 2023-08-08 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_upload", "0006_alter_uploadedfile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="user",
        ),
    ]
